### ISSUE TITLE
Find a new webchat solution for the discussion MUCs

### ISSUE THREAD

**Issue by xnyhps** [xsf/xmpp.org#101]
#58 removed the webchat links, as they were pointing to a squatted domain. However, it would be great to have a new webchat we can link people to.

**Comment by guusdk** [comment]
Do we still want to provide a webchat client? If so, what about providing a page that provides a webchat client on our own webserver? I'm expecting that people like @jcbrand or @benlangfeld would be willing to help out with that, if asked.

**Comment by ge0rg** [comment]
I consider having webchat access a very useful feature. I've evaluated the options for a similar use case (xmpp client support using anonymous access to a single MUC, with random-generated / editable nicknames) and the best option was [prosody's `chat.tar.gz`](https://op-co.de/blog/posts/prosody-webchat/) which is not a project, not packaged and not quite maintained.

[Candy](https://candy-chat.github.io/candy/) was a close second UX-wise (it only lacks randomly generated nicknames ;-) ).

IIRC there was also some movement to support this use case in [Converse.js](https://conversejs.org/).

My position would be to pick one that provides the best UX, all neutrality considerations aside. If there are multiple contenders, we can have the board vote on which one provides the nicest-looking Emoji.

**Comment by Neustradamus** [comment]
Like I have requested a long time ago:
Jappix (but the devel is now stopped except for security issues)

**Comment by jcbrand** [comment]
I'd be happy and willing to help out here by creating a solution with [Converse.js](https://conversejs.org).

I've been in discussion with @guusdk about making an "embedded" version of Converse.js for OpenFire and since then I've been working on making such a version possible.

The first demo was in my FOSDEM talk, where I embedded Converse.js in my talk slides.
See here: https://conversejs.org/slides/fosdem-2017/#/embedded-demo
(BTW, I see now the header is cut off if the page is zoomed to 100%, but this is simply a CSS issue).

What is currently not possible, which is possible with Candy AFAIK, is to show multiple rooms in this way. That's because Converse.js doesn't have support for tabs. If this is required, then I'll first have to add tabbing support, which I'm willing to do, but which will take a while still.

So, I'd like to know what features are required above an beyond what is shown in the above demo.
If none more are required, we could integrate it right away. Otherwise, please let me know and I'll get to work on adding those features.

**Comment by guusdk** [comment]
Although tabbed browsing would be a nice feature, it might also confuse the accidental drive-by visitor. Perhaps having a distinct page for each chat isn't the worst idea.  Plus, we can always improve on that later.

Perhaps you could prepare a PR for the site that integrates a converse-based chat with the as-is functionality?

**Comment by jcbrand** [comment]
Yes, I'll prepare a PR.

**Comment by SamWhited** [comment]
While a webchat would be nice, I'd prefer that we didn't use converse.js. I know of at least one XSS attack in it. I've already contacted jc about it, and it may already be fixed, but the fact that it exists at all doesn't fill me with confidence. Mistakes happen, but embedding user content in the DOM is a solved problem; as far as I'm concerned you only get one strike in that department; sorry if this sounds harsh, but we should attempt to protect our users.

While there's not a lot of informtaion on the xmpp.org domain to steal, something simpler with better vetting would make me happier personally.

**Comment by jcbrand** [comment]
Ok. I'm sorry to hear that. I fixed the issue you reported and the fix has been released.

I agree that such an obvious security hole doesn't inspire confidence, and I'll have to do some soul-searching with regards to how I let this happen and how I can avoid similar mistakes in the future.

**Comment by guusdk** [comment]
@SamWhited Although I do think it's a bit harsh, yes, I would not mind an alternative - but please do provide one.

**Comment by SamWhited** [comment]
@jcbrand many thanks; and please understand that I wasn't trying to target you specifically, I'd just like whatever client we use to be vetted first.

@guusdk I tried a bunch of web clients including several commercial services, and so far the only one I haven't been able to trivially script inject was the unmaintained prosody web chat tarball. I don't especially want to advocate for something that's not really maintained, but I also know the prosody folks use it and would most likely provide updates if and when issues are discovered, even if it's not an actively developed project feature wise. I'd love to know what other better maintained stuff people use though.

**Comment by guusdk** [comment]
Let's find a way to move forward.

@jcbrand apparently fixed converse.js - which is a good indication that the project is maintained. Can you re-vet that project, @SamWhited ? If so, and provided that you don't find anything, I'd prefer to move forward with converse.js. Not only is it actively maintained: we have someone here that is willing and able to do the integration work with our website.

**Comment by SamWhited** [comment]
I'm definitely not the person to do any sort of security audit; if I didn't find anything I don't think that would be enough to count as evidence that problems don't exist. The fact that an issue like that existed in the first place still really bothers me though, and even though JC did a great job of fixing it quickly I think converse.js (and most of these web chat things) are just too complicated and have too large of an attack surface to expose our users to them (especially if it's on every page and loaded even if you just visit the site like, presumably, converse.js would be since it's more of an overlay than a full page thing itself).

**Comment by horazont** [comment]
> especially if it's on every page and loaded even if you just visit the site like, presumably, converse.js would be since it's more of an overlay than a full page thing itself

Is that something we even want?

**Comment by guusdk** [comment]
Are you saying that you'd prefer to not have a webchat at the site at all?

From a UX perspective, I'd prefer a one-page / full page thingy for our website, by the way, which I think would be a better fit to this our website than a chat that follows you around on a trip though our website. As far as I know, converse.js supports that too. My preference for that isn't based on a security concern, but corresponds nicely with one of your concerns.

**Comment by SamWhited** [comment]
> Are you saying that you'd prefer to not have a webchat at the site at all?

No, just that if we have one it needs to be one-page (sounds like that's what we want anyways though,s o that works), and that we need to pick something that's not a giant full-fledged client with support for a million things. We need something simple with a smaller attack surface.

**Comment by horazont** [comment]
Without having looked in detail, the prosody thing may fit those requirements. @ge0rg You mention "buggy" in your blog post there, what exactly does that mean?

**Comment by guusdk** [comment]
@jcbrand - given all the new developments around Converse - should we give this another spin? I'd really love for a web client to be available, to pull in more people. It will help to onboard new members.

**Comment by wurstsalat3000** [comment]
@mwild1 since there is a working web chat solution in place, I guess this issue can be closed?

**Comment by mwild1** [comment]
Yup! :+1:
