### ISSUE TITLE
Packet obfuscation

### ISSUE THREAD

**Issue by testote** [xsf/xmpp.org#1021]
A library for packet obfuscation would be awesome to avoid traffic sniffing, MiTM and packet signalling. A standard would be more interesting than every implementation making its own version.

**Comment by Echolon** [comment]
Is this in the right section?

Can someone help what's the matter here. I don't fully understand unfortunately.

@ge0rg ?

**Comment by mwild1** [comment]
XMPP is an application-layer protocol. It is better to solve the issues you mentioned at a lower level, e.g. within TLS (for packet obfuscation and MITM prevention) which is a widely adopted internet standard, or even lower layers using tools/networks like Tor and I2P.

There has also been a lot of academic research happening into anonymous decentralized messaging (e.g. [Vuvuzela](https://news.mit.edu/2015/untraceable-anonymized-communication-guaranteed-1207)) that is resistant to timing analysis for example. However this problem is extremely difficult to solve in general, and unfortunately current proposals and implementations all have significant limitations - usually in the significant amount of bandwidth they require, which makes them unsuitable for use on battery-powered devices or metered connections.

I hope this helps point you in the right direction!
