### ISSUE TITLE
Client's view: Show all by default

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1132]
I wanted to recommend to show all clients by default and let the user make the first platform selection.

So maybe introduce "ALL" as button and have it selected by default

**Comment by wurstsalat3000** [comment]
Platform is now selected by the user-agent, see 09bb3b7275d9609965fe26300e50dcf36ad80f21

I introduced this "separated" layout in order to reduct the amount of information presented to the user. An "All" button would just display a cluttered list in my opinion. First platform selection is now taken from the user's browser-agent.
