### ISSUE TITLE
Software: Logo contrast can be unsufficient in light/dark theme

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1171]
![Screenshot_20220907_204909](https://user-images.githubusercontent.com/29168011/188955060-96facaed-554a-4172-9033-df2bbfb6179a.png)

**Comment by wurstsalat3000** [comment]
A filter using drop-shadow works for Profanity, but not for Poezio:

```
    filter: drop-shadow(0px 0px 6px rgba(150, 150, 150, 0.8));
```

![image](https://user-images.githubusercontent.com/35428560/192449894-9b3fa0a2-8a2d-4341-9486-376be44372f2.png)

**Comment by wurstsalat3000** [comment]
It all comes down to how these logos are designed. Some work good on both light and dark backgrounds, some only on light backgrounds. I haven't observed logos which only work on dark backgrounds, so the only solution I see here is to add a light colored box to the logo's background.

**Comment by wurstsalat3000** [comment]
Closing this as invalid. Regardless of how we try to approach this, it will always be an issue of the logo itself. If we added a box with sufficient contrast (meaning almost white), this would also deteriorate the look of every other logo.

Just a simple example: How would a desktop environment render this, if the desktop background was black? It would fail, because the logo wasn't designed with dark backgrounds in mind.
