### ISSUE TITLE
Minor: Show supported XEPs right away

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1175]
I don't know if this is performance and load trade-off, but I'd suggest to show it right away.

**Comment by wurstsalat3000** [comment]
I added a `collapse` with a toggle button on purpose, because this page is intended for users searching for a client (server/library). Listing all supported XEPs by default has no benefit for users. That's one reason why there are Compliance Suites: to abstract supported standards. Compliance results are displayed prominently on each page. If users want to see all XEPs, they can click the toggle button.
