### ISSUE TITLE
Create separate directory and clean up for newsletter blogpost

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1287]
I think its getting a mess.

Maybe lets wait after the next release

**Comment by cal0pteryx** [comment]
I don't think this would be really necessary. All posts are sorted by date and we have "newsletter" in the file name.

Putting newsletter posts in a "newsletter" subdirectory would mess up the URL structure, which is https://xmpp.org/2023/06/the-xmpp-newsletter-may-2023/ aligned to all the other blog posts at the moment.

Also this would require a lot of manual work, since aliases would be necessary to generate redirects..
