### ISSUE TITLE
Composite feedback for xmpp.org, providers.xmpp.net and related entities

### ISSUE THREAD

**Issue by HansLachman** [xsf/xmpp.org#1419]
I have a long list of feedback items, including practical suggestions for improvement of the xmpp.org site, the providers.xmpp.net site, and related entities (client sites and provider sites).  New to XMPP, I was trying to register an account and ran into various roadblocks and misdirections.  I carefully documented the steps I took, what went wrong along the way, and my suggestions for how to improve the process for ordinary users who want to sign up for XMPP.  Some of the suggested improvements are for the xmpp.org website content (including providers.xmpp.net, since the two sites appear to be related).  As for my other suggestions, e.g., relating to client sites and provider sites, if you have a way to relay the issues to the responsible parties, please help (I've had a hard time figuring out how to get support from the various entities).  The documentation of the steps I took, and the associated feedback and suggestions, is 11.7 KBytes long, so it's attached as a TXT file.  Thank you for your attention to my input.
[xmpp-adv.txt](https://github.com/user-attachments/files/16462007/xmpp-adv.txt)

**Comment by cal0pteryx** [comment]
Hi and thanks for your feedback, it is appreciated.

1. xmpp.earth is not related to xmpp.org/net. It looks like xmpp.earth does not allow to register through their website, but only through a client. This indeed leads to a circle, because xmpp.earth is linking to movim.eu, while movim.eu is linking back to xmpp.earth. @edhelas how would I create an account on xmpp.earth through Movim? Is that possible?

2. I see that you already created tickets in the appropriate places, thanks! I believe these issues should be fixed soon.

3. I have forwarded your suggestions to the team of providers.xmpp.net (which I am part of). Concerning your remarks about 404.city: Please contact them at support@404.city, since xmpp.org/net is not affiliated with them.

4. I believe it's intentional that on movim.eu, other instances are promoted in order to distribute users evenly accross instances. Otherwise all users would register on this single instance. In any way, please direct this feedback to Movim, which is available here: https://github.com/movim/movim

5. Please open an issue at the Converse.js project on GitHub

6. Please contact Movim directly
7. These are for the Converse.js / Movim developers

Please note that it is planned to revise the /getting-started page at xmpp.org, see #1259 

Thanks again for your feedback!
