### ISSUE TITLE
Inconsistency in sponsorship perks listing

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#175]
http://xmpp.org/community/sponsorship.html lists the benefits for sponsors, in a table view, as well as a descriptive text. The two listings differ:
- The table view contains "Logo in Site Sidebar", which is not in the "benefits in detail" section.
- The "benefits in detail" section contains "Logo Site Home Page", which is not in the table view.

Most pages do not have sidebars, although the logos currently appear to be present in the footer of every page, including the home page.

Should both texts be replaced with "Logo on every page"?

**Comment by bear** [comment]
I'll have to check, I think the logo on every page is a perk of one of the higher level sponsor packages.

**Comment by dwd** [comment]
The perks are indeed fixed in advance, and are (in a blandly legal sense) what sponsors are paying for. Board can change this for *future* sponsors, and since the Board essentially leaves sponsors on the site until replaced, not all the listed sponsors may be under contract, so changing it might not involve negotiation with each sponsor.

I suggest that Board and the Web folks work together to decide where Sponsor logos could go, and then redefine the perks for future sponsors (and go get some more).

**Comment by guusdk** [comment]
As one of the web folks, I would be happy to facilitate this. @dwd, could you raise this at the next board meeting, possibly adding a reminder on https://trello.com/b/Dn6IQOu0/board-meetings (where I lack the privilege to do so)?

**Comment by dwd** [comment]
I'm not a Board member, so no more than you can. I'd flag this with @ralphm

**Comment by guusdk** [comment]
Ah, the Trello board member list suggests that you technically are able to add things there.

**Comment by dwd** [comment]
Oh. So I can. That's probably an error, but I'll use it anyway.

**Comment by guusdk** [comment]
Board OK'd the PR in the board meeting of Wednesday April 12th, 2017.
