### ISSUE TITLE
404 for http://xmpp.org/registrar/

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#194]
Seems like a redirect would be good from http://xmpp.org/registrar/ to [where are the registrar pages now??]

**Comment by SamWhited** [comment]
I think the page doesn't exist at the moment. @Kev made https://github.com/xsf/registrar the other day, so we can probably use that as the source for generating new pages.

**Comment by stpeter** [comment]
Aha OK! Perhaps the split of schemas and registries into separate repos wasn't always the best idea, but we'll work it out. ;-)

**Comment by Kev** [comment]
If we want to merge the XEP and Registrar repos, we can do so.

**Comment by tfar** [comment]
@stpeter The schemas don't even have a repo at the moment. In the end it doesn't matter if it's all in one repo or in distinct repos, but if the schemas are important, they should be somewhere, not just on a static gitorious or non-public disk.

**Comment by SamWhited** [comment]
I think it definitely makes sense to have the schemas live with the XEPs (since they both effectively describe different parts of the same abstract "protocol"), but I'm not sure that we'd want the registry in the same repo (though I don't have any argument for or against, just a vague feeling that we'd want to be able to track the protocol / registry history separately). I don't have strong feelings either way though.

**Comment by bear** [comment]
The only reason, IMO, to have a different repo is if different teams will manage/update the data.

If the registry is managed by the same editorial team as the XEPs then having two repos seems like overkill. Since the registrar repo is new we can just remove it and add the data to the XEPs repo, give it a test and if we don't like it, move it out.

**Comment by SamWhited** [comment]
:+1: makes good sense to me.

**Comment by Flowdalic** [comment]
> If the registry is managed by the same editorial team as the XEPs

This may not be true forever, as explicitly stated by XEP-0054 § 2. Also two repos is IMHO not that much overkill (in general and compared to ideas within the XSF to have a repo per XEP ;)).

**Comment by tfar** [comment]
The 404 is gone. See http://xmpp.org/registrar/ .

**Comment by bear** [comment]
fixed with commit https://github.com/xsf/xmpp.org/commit/37ac50c04bd9a268211bec1efd679ceecf8e7030
