### ISSUE TITLE
Registrar related redirects

### ISSUE THREAD

**Issue by tfar** [xsf/xmpp.org#204]
Create permanent redirects for //xmpp.org/registrar and //xmpp.org/registrar/ to xmpp.org/registrar/index.html.

**Comment by SamWhited** [comment]
Why to `index.html`? That seems ugly; wouldn't we want the redirects for `registrar/index.html` and `registrar` to go to `registrar/`?

**Comment by bear** [comment]
nginx can be told to look for foo/ and foo/index.html without the incoming url having to be rewritten

then if we do a redirect of foo -> foo/  we are covered

the reason for it is way back in the original design of HTTP and HTML, which everyone who codes in javascript seems to want to forget, ignore or otherwise just not care,  foo/ means give me the index page for the resource foo so web servers have a default index.html set for anything ending in /

**Comment by tfar** [comment]
I'm happy either way, as long we make sure to link to registrar/.

**Comment by Kev** [comment]
On 3 Aug 2016, at 22:45, T Markmann <notifications@github.com> wrote:
> Create permanent redirects for //xmpp.org/registrar and //xmpp.org/registrar/ to xmpp.org/registrar/index.html.

I’m not sure I understand this. /registrar already redirects to /registrar/, which seems to be correct. We shouldn’t have index.html in our URLs anywhere.

/K

**Comment by SamWhited** [comment]
It definitely doesn't redirect for me.

**Comment by Kev** [comment]
On 4 Aug 2016, at 20:50, Sam Whited <notifications@github.com> wrote:
> It definitely doesn't redirect for me.

No, I was being stupid, I meant that it served the same content from disk.

/K

**Comment by Kev** [comment]
On 4 Aug 2016, at 20:50, Sam Whited <notifications@github.com> wrote:
> It definitely doesn't redirect for me.

I think it does now?

/K

**Comment by tfar** [comment]
It does. The index.html link doesn't to redirect to the non index.html one though. If that's possible at all.
