### ISSUE TITLE
add more specific platforms in clients.json

### ISSUE THREAD

**Issue by goffi-contrib** [xsf/xmpp.org#350]
currently the platforms allowed in data/clients.json are:

>     Android
>     Browser
>     BSD
>     iOS
>     Linux
>     macOS
>     Other
>     Solaris
>     Windows

But it's not specific enough:

- Linux should be GNU/Linux, as we are talking about GNU/Linux distributions (otherwise Android is a Linux too)
- we should have CLI (Command Line Interface) and TUI (Text User Interface) as several clients are in those categories

**Comment by SamWhited** [comment]
> Linux should be GNU/Linux

Except when it's not. Everyone knows what we mean and what it will run on when you say "Linux" there's no need to be any more specific than this.

**Comment by ge0rg** [comment]
I also think that we need less categories, not more. This list is meant for newcomers!

Power users with a black belt in google-fu will figure out their CLI-scriptable TUI-enabled asynchronous XMPP framework on their own. What we need here is a rough overview so that a new user can get a short list of possible alternatives.

**Comment by goffi-contrib** [comment]
A sysadmin who needs a XMPP client to work on a server without GUI (which is definitely not a corner case) needs to know if a client is usable in a console, this information was available before and it is not anymore. Without that, he will need to check every client official website to know it.

**Comment by horazont** [comment]
I am split on this.

On the one hand, I think even tech nerds need a way to discover XMPP clients suited for their use. I don’t exactly recall how I came across e.g. poezio, but I know that it wasn’t a simple task. On the other hand, making the list too complex is something I’d like to avoid (actually, I think that having more than one client per platform new users need to choose from already puts us behind competition).

I think the ideal case would be to have a filterable list like the XEP list, with the non-common platforms hidden by default and an additional switch for GUI vs. TUI, because that’s not really a platform and you can have a TUI windows client which doesn’t work on Linux (I know).

This requires quite a bit of work though. Someone could take a look in how the XEP table is implemented and whether and how it’s possible to port that to the software directories.

I’m definitely against further expanding the platforms list.

**Comment by ge0rg** [comment]
Both Google and ddg turn up profanity, poezio and mcabber on the first page for "console xmpp client". I think it's not a stretch to require this level of problem solving capability from a Linux system administrator. 

Anyhow, our first target should be new users, and we can hide all the nifty combinations of CUI, TUI and MIUI behind a "more /advanced" link. But before we go that route, we need to fix our recommendation for normal people.

**Comment by guusdk** [comment]
I'm closing this as a 'no-fix'. Adding more details is very likely to result in more discussion on the correctness of those details, while in return, very little value is gained. Let's keep it simple.
