### ISSUE TITLE
Setup beta.xmpp.org to pre-build pull requests

### ISSUE THREAD

**Issue by imaginator** [xsf/xmpp.org#96]
Current situation:
- pull request received
- manual html and markdown checked
- merge content
- hope that the build is sensible

Better situation:
- pull request received
- github fires a travis build
- build is published to beta.xmpp.org
- review beta.xmpp.org
- merge content (with more confidence)

**Comment by guusdk** [comment]
Since this issue was created, Travis did get introduced, and does some sanity checks that were recently improved upon. 

Although I like the idea of a staging server, it does not seem likely that this will happen, given the absolute inactivity of this issue in the last year and a half.

Let's reopen or recreate this issue when new momentum is gained.
